/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Arayuz;

import Services.KitapTurService;
import Services.Mesajlar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author drhal
 */
public class KitapTur extends javax.swing.JFrame {

    /**
     * Creates new form KitapTur
     */
    public KitapTur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldAdi = new javax.swing.JTextField();
        jTextFieldID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKitapTur = new javax.swing.JTable();
        jButtonEkle = new javax.swing.JButton();
        jButtonGuncelle = new javax.swing.JButton();
        jButtonSil = new javax.swing.JButton();
        jButtonListele = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Kitap Tür");

        jLabel2.setText("Kitap Tür Adı");

        jTableKitapTur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Adi"
            }
        ));
        jScrollPane1.setViewportView(jTableKitapTur);

        jButtonEkle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ekle.png"))); // NOI18N
        jButtonEkle.setText("Ekle");
        jButtonEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEkleActionPerformed(evt);
            }
        });

        jButtonGuncelle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/duzenle.png"))); // NOI18N
        jButtonGuncelle.setText("Güncelle");
        jButtonGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuncelleActionPerformed(evt);
            }
        });

        jButtonSil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sil.png"))); // NOI18N
        jButtonSil.setText("Sil");
        jButtonSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSilActionPerformed(evt);
            }
        });

        jButtonListele.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/liste.png"))); // NOI18N
        jButtonListele.setText("Listele");
        jButtonListele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListeleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jTextFieldAdi))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonEkle)
                        .addGap(46, 46, 46)
                        .addComponent(jButtonGuncelle)
                        .addGap(58, 58, 58)
                        .addComponent(jButtonSil)
                        .addGap(56, 56, 56)
                        .addComponent(jButtonListele)))
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(221, 221, 221)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(156, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldAdi, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEkle)
                    .addComponent(jButtonGuncelle)
                    .addComponent(jButtonSil)
                    .addComponent(jButtonListele))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(236, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(166, 166, 166)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(522, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEkleActionPerformed
        // TODO add your handling code here:

        String adi=jTextFieldAdi.getText().trim();
        new KitapTurService().Ekleme(adi);

        //Listele();
        AzalanSekildeListele();
        Temizle();
    }//GEN-LAST:event_jButtonEkleActionPerformed

    private void jButtonGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuncelleActionPerformed
        // TODO add your handling code here:

        String secilenID= jTextFieldID.getText().trim();
        if (secilenID!=null && secilenID.length()>0) {
            String adi=jTextFieldAdi.getText().trim();
           
            int ID=Integer.parseInt(secilenID);
            new KitapTurService().Guncelleme(ID, adi);

            Listele();
            Temizle();

        }else{
            JOptionPane.showMessageDialog(null, new Mesajlar().SatirSeciniz());
        }
    }//GEN-LAST:event_jButtonGuncelleActionPerformed

    private void jButtonSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSilActionPerformed
        // TODO add your handling code here:

        String secilenID= jTextFieldID.getText().trim();
        if (secilenID!=null && secilenID.length()>0) {

            int ID=Integer.parseInt(secilenID);
            new KitapTurService().Silme(ID);

            Listele();
            Temizle();
        }else{
            JOptionPane.showMessageDialog(null, new Mesajlar().SatirSeciniz());
        }
    }//GEN-LAST:event_jButtonSilActionPerformed

    private void jButtonListeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListeleActionPerformed
        // TODO add your handling code here:
        Listele();
        Temizle();
    }//GEN-LAST:event_jButtonListeleActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jTextFieldID.hide();
    }//GEN-LAST:event_formWindowOpened

    public void AzalanSekildeListele(){
        DefaultTableModel model=(DefaultTableModel)jTableKitapTur.getModel();
        model=new KitapTurService().AzalanSekildeGetir(model);
    }
    
    public void Listele(){        
        DefaultTableModel model=(DefaultTableModel)jTableKitapTur.getModel();
        model=new KitapTurService().Getir(model);        
    }
    
    public void Temizle(){
        jTextFieldID.setText("");
        jTextFieldAdi.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KitapTur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KitapTur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KitapTur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KitapTur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KitapTur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEkle;
    private javax.swing.JButton jButtonGuncelle;
    private javax.swing.JButton jButtonListele;
    private javax.swing.JButton jButtonSil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableKitapTur;
    private javax.swing.JTextField jTextFieldAdi;
    private javax.swing.JTextField jTextFieldID;
    // End of variables declaration//GEN-END:variables
}
