/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Arayuz;

import Services.KitapYazarService;
import Services.Mesajlar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author drhal
 */
public class KitapYazar extends javax.swing.JFrame {

    /**
     * Creates new form KitapYazar
     */
    public KitapYazar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldAdi = new javax.swing.JTextField();
        jTextFieldSoyadi = new javax.swing.JTextField();
        jButtonEkle = new javax.swing.JButton();
        jButtonGuncelle = new javax.swing.JButton();
        jButtonSil = new javax.swing.JButton();
        jButtonListele = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKitapYazar = new javax.swing.JTable();
        jTextFieldID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldKimlikNo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Yazar Soyadı");

        jLabel2.setText("Yazar Adı");

        jButtonEkle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ekle.png"))); // NOI18N
        jButtonEkle.setText("Ekle");
        jButtonEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEkleActionPerformed(evt);
            }
        });

        jButtonGuncelle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/duzenle.png"))); // NOI18N
        jButtonGuncelle.setText("Güncelle");
        jButtonGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuncelleActionPerformed(evt);
            }
        });

        jButtonSil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sil.png"))); // NOI18N
        jButtonSil.setText("Sil");
        jButtonSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSilActionPerformed(evt);
            }
        });

        jButtonListele.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/liste.png"))); // NOI18N
        jButtonListele.setText("Listele");
        jButtonListele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListeleActionPerformed(evt);
            }
        });

        jTableKitapYazar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Adı", "Soyadı", "KimlikNo"
            }
        ));
        jTableKitapYazar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableKitapYazarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableKitapYazar);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Kitap Yazar");

        jLabel4.setText("Yazar Kimlik No");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jButtonEkle)
                                .addGap(46, 46, 46)
                                .addComponent(jButtonGuncelle)
                                .addGap(58, 58, 58)
                                .addComponent(jButtonSil)
                                .addGap(56, 56, 56)
                                .addComponent(jButtonListele))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(jTextFieldID, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(jTextFieldAdi)
                            .addComponent(jTextFieldSoyadi)
                            .addComponent(jTextFieldKimlikNo, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldSoyadi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldKimlikNo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonEkle)
                            .addComponent(jButtonGuncelle)
                            .addComponent(jButtonSil)
                            .addComponent(jButtonListele))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEkleActionPerformed
        // TODO add your handling code here:

        String adi=jTextFieldAdi.getText().trim();
        String soyadi=jTextFieldSoyadi.getText().trim();
        String kimlikNo=jTextFieldKimlikNo.getText().trim();
        
        boolean result=new KitapYazarService().Ekleme(adi, soyadi,kimlikNo);
        
        if(result==true){
            Listele();
            Temizle();       
        }else{
            JOptionPane.showMessageDialog(null, new Mesajlar().IslemBasarisiz(), "Hata", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonEkleActionPerformed

    private void jButtonGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuncelleActionPerformed
        // TODO add your handling code here:

        String secilenID= jTextFieldID.getText().trim();
        if (secilenID!=null && secilenID.length()>0) {
            String adi=jTextFieldAdi.getText().trim();
            String soyadi=jTextFieldSoyadi.getText().trim();
            String kimlikNo=jTextFieldKimlikNo.getText().trim();
            int ID=Integer.parseInt(secilenID);
                        
            boolean result=new KitapYazarService().Guncelleme(ID, adi, soyadi, kimlikNo);
            
            if(result==true){
            
            Listele();
            Temizle();
            }else{
                JOptionPane.showMessageDialog(null, new Mesajlar().IslemBasarisiz(), "Hata", JOptionPane.ERROR_MESSAGE);
            }
            
        }else{
              JOptionPane.showMessageDialog(null, new Mesajlar().SatirSeciniz());  
            }  

    }//GEN-LAST:event_jButtonGuncelleActionPerformed

    private void jButtonSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSilActionPerformed
        // TODO add your handling code here:
       
        String secilenID= jTextFieldID.getText().trim();
        if (secilenID!=null && secilenID.length()>0) {  
            
            int ID=Integer.parseInt(secilenID);
            boolean result=new KitapYazarService().Silme(ID);
            
            if(result==true){
            Listele();
            Temizle();
            }else{
                JOptionPane.showMessageDialog(null, new Mesajlar().IslemBasarisiz(), "Hata", JOptionPane.ERROR_MESSAGE);
            }
        }else{
              JOptionPane.showMessageDialog(null, new Mesajlar().SatirSeciniz());  
        }  
    }//GEN-LAST:event_jButtonSilActionPerformed

    private void jButtonListeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListeleActionPerformed
        // TODO add your handling code here:
        Listele();
        Temizle();
    }//GEN-LAST:event_jButtonListeleActionPerformed

    private void jTableKitapYazarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableKitapYazarMouseClicked
        // TODO add your handling code here:

       DefaultTableModel model=(DefaultTableModel)jTableKitapYazar.getModel();
       int secilen=jTableKitapYazar.getSelectedRow();
        
       jTextFieldID.setText(model.getValueAt(secilen,0).toString());
       jTextFieldAdi.setText(model.getValueAt(secilen,1).toString());
       jTextFieldSoyadi.setText(model.getValueAt(secilen,2).toString());
       jTextFieldKimlikNo.setText(model.getValueAt(secilen,3).toString());
    }//GEN-LAST:event_jTableKitapYazarMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        jTextFieldID.hide();
    }//GEN-LAST:event_formWindowOpened

    
    public void Temizle(){
        
        jTextFieldID.setText("");
        jTextFieldAdi.setText("");
        jTextFieldSoyadi.setText("");  
        jTextFieldKimlikNo.setText("");
    }    
    
    
    public void Listele(){
        DefaultTableModel model=(DefaultTableModel)jTableKitapYazar.getModel();
        model=new KitapYazarService().Getir(model);      
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KitapYazar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KitapYazar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KitapYazar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KitapYazar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KitapYazar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEkle;
    private javax.swing.JButton jButtonGuncelle;
    private javax.swing.JButton jButtonListele;
    private javax.swing.JButton jButtonSil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableKitapYazar;
    private javax.swing.JTextField jTextFieldAdi;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldKimlikNo;
    private javax.swing.JTextField jTextFieldSoyadi;
    // End of variables declaration//GEN-END:variables
}
